#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.
$OPENSHIFT_RUNTIME_DIR/bin/pip install --use-mirrors -r $OPENSHIFT_REPO_DIR/requirements.txt

