#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then
# install python 2.7.3
cd $OPENSHIFT_TMP_DIR
wget http://python.org/ftp/python/2.7.3/Python-2.7.3.tar.bz2
tar jxf Python-2.7.3.tar.bz2
cd Python-2.7.3
./configure --prefix=$OPENSHIFT_DATA_DIR
make ; make install

export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH

# install setuptools and pip
cd $OPENSHIFT_TMP_DIR
wget http://pypi.python.org/packages/source/s/setuptools/setuptools-0.6c11.tar.gz
tar zxf setuptools-0.6c11.tar.gz
cd setuptools-0.6c11
python setup.py install
cd $OPENSHIFT_TMP_DIR
wget http://pypi.python.org/packages/source/p/pip/pip-1.1.tar.gz
tar zxf pip-1.1.tar.gz
cd pip-1.1
python setup.py install

# set path
export PATH=$OPENSHIFT_DATA_DIR/bin:$PATH

# install uwsgi
pip install uwsgi

# cleanup
cd $OPENSHIFT_TMP_DIR
rm -rf Python-2.7.3.tar.bz2
rm -rf setuptool-0.6c11.tar.gz
rm -rf pip-1.1.tar.gz

fi